version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "456123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    restart: always
    environment:
      PORT: "8080"
      DATABASE_URL: "postgresql://postgres:456123@db:5432/dateplanner?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
